### ISSUE TITLE
Connection failed for Shearwater Perdix AI

### ISSUE THREAD

**Issue by AndLindemann** [libdivecomputer/libdivecomputer#17] opened 2020-11-01 13:06 UTC
Since recently (might have been the last firmware update), I fail to connect to our 2 Perdix AI computers from Divinglog, which I suppose uses libdivecomputer. The error is the same for both devices:

00:00:000   INFO: 2020-11-01 13:01:18
00:00:005   INFO: Libdivecomputer version: 0.7.0-devel (3e89e1b871d41b42f8411702984cdc20c1d82fc8)
00:00:008   INFO: Diving Log version: 6.0.19.0
00:00:010   INFO: Windows version: Windows 10 ( | Build 19041), 6.3.19041
00:00:014   INFO: OnlyNewDives=True, FingerprintAvailable=True, LastDiveDate=20.08.2020 12:01:00
00:00:017   INFO: Start download (BLE): Shearwater Perdix AI
00:00:520   INFO: Connecting to: BluetoothLE#BluetoothLE00:1a:7d:da:71:14-de:44:3a:93:2f:19
00:00:559   INFO: 3 services found
00:00:563   INFO: Is paired=True
00:00:566   INFO: Protection level=Encryption
00:00:658   INFO: Unpair device=Unpaired
00:00:670   INFO: Device is paired=False
00:00:751   INFO: BLE connected
00:01:019   INFO: Custom Pairing Kind: ConfirmOnly
00:01:022   INFO: Custom Pairing Pin: 
00:01:034   INFO: Pairing device=Paired
00:01:155   INFO: Paired device name=Perdix
00:01:161   INFO: 1 services found
00:01:164   INFO: 1 services found
00:01:167   INFO: 00001801-0000-1000-8000-00805f9b34fb
00:01:171   ERROR: Service not found: fe25c237-0ece-443c-b0aa-e02033e7029d
00:01:174   ERROR: DC_STATUS_IO

I'm completely at a loss here. The Shearwater Cloud software can find and connect to the computers just fine, so it doesn't seem to be a general bluetooth issue with my PC.
Both Perdix AIs are running FW v81/BT09

**Comment by jefdriesen** [comment] 2020-11-03 10:23
It looks like the problem happens during setting up the bluetooth connection. That's even before libdivecomputer comes into play. I'll forward the report to the Diving Log developer to have a look.

One thing that's a bit unusual is the service not found error. That might indicate Diving Log is trying to connect to the wrong bluetooth device (but a few lines earlier, it does say "Perdix" as the paired device), or the service uuid has changed after the firmware upgrade (also rather unlikely).

The Shearwater dive computers are known to somehow remember the device they are paired with, which makes it difficult to use them on two devices (e.g. laptop and mobile phone). But I assume you are running Shearwater Cloud on the same system, so that's not the issue here?

**Comment by AndLindemann** [comment] 2020-11-03 10:43
Yes, that's correct. I run Shearwater Cloud on the same system so that shouldn't be an issue. Thanks for forwarding this!

**Comment by divinglog** [comment] 2020-11-03 12:59
I got several reports like this recently, and always the BLE service is not found. I think it is related to the latest Windows 10 20H1/H2 update and some API changes. One user reported that uninstalling Shearwater (Cloud) Desktop worked for him, but this is not confirmed yet. But this is not a libdivecomputer issue, because it happens before libdc is even used. Please contact me via email and I'll send you a beta version which you could try.

**Comment by jefdriesen** [comment] 2021-06-07 07:58
Closing because issue is not in libdivecomputer.

**Closed by jefdriesen** 2021-06-07 07:58 UTC
