### ISSUE TITLE
Bluetooth - Dive download from Ratio i3XM stuck at getting list of dives after downloading 4 dives. #2424

### ISSUE THREAD

**Issue by linuxcrash** [libdivecomputer/libdivecomputer#13] opened 2019-12-11 17:38 UTC
I already reported this on the Subsurface issue list. Not sure if it's ok to crossref it here.

The link to the Subsurface issue is:
https://github.com/Subsurface-divelog/subsurface/issues/2424#issue-533883685

**Comment by jefdriesen** [comment] 2019-12-12 09:57
At first sight, this looks like a problem in subsurface, because I don't see anything unusual. Those "Received NAK packet with error code 60" are harmless. But just to double check, can you try to download your dives with the libdivecomputer command-line tool?

Download the [linux build](https://libdivecomputer.org/builds/stable/linux/dctool) and execute with these options:
```
chmod +x dctool
./dctool -vv -l idive.log -f idive download -o dive.%n.bin -f raw -t bluetooth
```
Email me the idive.log and all the dive.*.bin files (or attach them to the ticket if you don't mind making your data public).

**Comment by linuxcrash** [comment] 2019-12-12 19:27
Hi Jef,
I tried the dctool but it seems there is an issue connecting properly to the i3XM. I only get a protocol error using your comand.

If I change the command to:
`
./dctool -d "Ratio iX3M GPS Tech+" -l ratio.txt -v download -o dive.%n.bin -f raw -t bluetooth
`
Then the download of the dives goes through 100%.

Error Log with your command:
[idive.log](https://github.com/libdivecomputer/libdivecomputer/files/3957416/idive.log)

Successful download (log and bin files):
[Ratio_i3xm.zip](https://github.com/libdivecomputer/libdivecomputer/files/3957478/Ratio_i3xm.zip)

Now does that mean its a Subsurface bug when it does not work there or are they bundling an older version of libdivecomputer that is not fully supporting the Ratio DC?

**Comment by jefdriesen** [comment] 2019-12-13 12:01
The command failed because I omitted the "-m 0x24" option to select the correct model. My mistake, but it looks you already solved that with the -d option.

The download was successful. There were a couple of minor errors, but nothing the built-in retry mechanism couldn't handle. So that means the problem is most likely somewhere in subsurface. There have not been any relevant changes to the Ratio code lately, so I would be surprised if the version used by subsurface is outdated. Unless you are using some *very* old subsurface version of course.

**Comment by linuxcrash** [comment] 2019-12-13 12:04
Ok that is interesting. I have used the latest available Subsurface AppImage with fixed bluetooth bug. I will have another look then into this using Subsurface and creating additional logs.

**Comment by jb2cool** [comment] 2020-03-08 00:54
@linuxcrash there have been some updates to Subsurface and libdivecomputer recently, would you be willing to try a recent test build (https://github.com/Subsurface-divelog/subsurface/releases/tag/ci-release) to see if this resolves your issue? This has a newer libdivecomputer and has improved Ratio communications for another user.

**Comment by linuxcrash** [comment] 2020-03-08 12:13
@jb2cool it seems the CI-release does only contain the sources for subsurface. I tried to get them compiled on my Feodara system following INSTALL.md but no luck so far. 
I would be happy to restest once I either have the AppImage version or I can get the thing compiled.

**Comment by jb2cool** [comment] 2020-03-08 12:55
These releases are rebuilt every time we update the master branch of our repo. So when you check, there may be some builds missing. The File you are looking for should be a file named "Subsurface.AppImage". If it is missing when you get around to try and download it, please drop me a line so I can make sure that a new build is triggered.

**Comment by linuxcrash** [comment] 2020-03-08 13:25
@jb2cool Ok got it now compiled.

Unfortunately it seems there is some bug with connecting to the Ratio using bluetooth. From the behavior I see, it seems more to be on the Ratio side. 

I paired the Ratio with my laptop which was fine. Then I moved the Ratio out of PC Mode and then back into it because I thought this might properly reinitialize the bluetooth parts of it. When I tried to download the dives, Subsurface/Laptop would not even be able to open a data connection to the Ratio and on the screen of the Ratio it only showed READY for Cable and Data.
I then wanted to ensure my Ratio has the latest firmware so I connected it using the USB cable and run the Firmware utility (Ratio Toolbox on Linux) and it found the Ratio and all looked up to date. I disconnected the Ratio again and then thought I start writing this comment here but to properly report my infos I followed step by step what I did. 

At this point I would start Subsurface again from terminal and put the Ratio in PC Mode. Now I went in and followed below procedure and suddenly it would at least open a Data connection and start reading the dives.

1. Paired the ratio in Gnome with my laptop and that went fine.
2. Started subsurface from terminal.
3. Import > Import from divecomputer.
4. Select Choose bluetooth download mode.
5. Click on Scan.
6. Select the DS000000 entry from the paired ratio.
7. Click Save.
8. Click Download
9. Wait 15+ minutes ( I have over 80 dives to download) without seeing the progress bar moving in Subsurface.
10. Abort download as nothing seems to happen and be stuck.
11. Retried but this time the data connection would again not be able to be established.

**Subsurface Output**
`
Subsurface: v4.9.3-1048-g7d9e907681cd, built with libdivecomputer v0.7.0-devel-Subsurface-NG (0714e327b70bb08f5289c9781c09dc10884881c9)
`

**Terminal Ouput**
`
Detecting bluetoothd version
Using /proc/<pid>/exe
Using /proc/<pid>/cmdline
Detected bluetoothd version 5.52
Bluetoothd: "5.52"
Using Bluetooth dbus socket implementation
Bluez 5 detected.
Registering client profile on "/qt/btsocket/Subsurface210499/2912473940" with options:
QMap(("Name", QVariant(QString, "QBluetoothSocket-210499"))("Role", QVariant(QString, "client"))("Service", QVariant(QString, "00001101-0000-1000-8000-00805f9b34fb")))
Profile Context: New Connection
INFO: dc_device_open error value of 0
[4.377248] ERROR: Received NAK packet with error code 60. [in src/divesystem_idive.c:357 (divesystem_idive_packet)]
[8.940060] ERROR: Received NAK packet with error code 60. [in src/divesystem_idive.c:357 (divesystem_idive_packet)]
[13.742636] ERROR: Received NAK packet with error code 60. [in src/divesystem_idive.c:357 (divesystem_idive_packet)]
`

**Current setup**
- Fedora 31 XPS 15 - Linux beexps 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Ratio iX3M 4.0.70/014

**Comment by dirkhh** [comment] 2020-03-08 15:16
This is something where @torvalds is most likely to be able to help.
He's traveling, but I'll ping him to take a look

**Comment by torvalds** [comment] 2020-03-08 16:01
Hmm. So this is legacy bluetootgh, not BLE, right?

Can you enable the "Save libdivecomputer logfile" and post the output?

**Comment by linuxcrash** [comment] 2020-03-08 16:53
@torvalds, good question. My laptop is capable of handling BT 4.2 (Intel Corporation Wireless 8265 / 8275 (rev 78) but I'm not sure what the Ratio divecomputer can handle.

In between this post and my previous post I noticed that I was missing the latest updates on Bluez which I now have installed and it seems that at least I can now reliably connect to the Ratio from Subsurface. It even starts to download the dives but after dive #3 it gets stuck. I tried this multiple times (CTRL+C'd it after about 10min waiting and no progress shown in the UI).

![Screenshot from 2020-03-08 17-32-39](https://user-images.githubusercontent.com/5081159/76167272-abcab080-6165-11ea-9d37-c40b42abfeee.png)


**Terminal Ouput from Subsurface**
`
Bluez 5 detected.
Missing CAP_NET_ADMIN permission. Cannot determine whether a found address is of random or public type.
Creating QtBluezDiscoveryManager
Discovered:  "00:18:09:15:C6:D8" "MDR-1RBT" Num UUIDs 5 total device 0 cached RSSI 0 Class 2360324 Num ManufacturerData 0
Discovered:  "28:11:A5:38:7C:45" "LE-Bose QC35 II" Num UUIDs 11 total device 1 cached RSSI 0 Class 2360344 Num ManufacturerData 0
Discovered:  "88:6B:0F:3D:EF:64" "DS000000" Num UUIDs 2 total device 2 cached RSSI 0 Class 7936 Num ManufacturerData 0
Discovered:  "40:49:0F:3F:29:C2" "KD-49XD8305" Num UUIDs 1 total device 3 cached RSSI -91 Class 0 Num ManufacturerData 0
Updating RSSI for "40:49:0F:3F:29:C2" QVariant(short, -93)
Updating ManufacturerData for "40:49:0F:3F:29:C2"
Updating RSSI for "88:6B:0F:3D:EF:64" QVariant(short, -70)
Updating RSSI for "40:49:0F:3F:29:C2" QVariant(short, -91)
Updating RSSI for "40:49:0F:3F:29:C2" QVariant(short, -91)
void QBluetoothDeviceDiscoveryAgentPrivate::stop()
Detecting bluetoothd version
Using /proc/<pid>/exe
Using /proc/<pid>/cmdline
Detected bluetoothd version 5.53
Bluetoothd: "5.53"
Using Bluetooth dbus socket implementation
Registering client profile on "/qt/btsocket/Subsurface28301/4028998270" with options:
QMap(("Name", QVariant(QString, "QBluetoothSocket-28301"))("Role", QVariant(QString, "client"))("Service", QVariant(QString, "00001101-0000-1000-8000-00805f9b34fb")))
Profile Context: New Connection
INFO: dc_device_open error value of 0
`

Attached the logfile as requested.
[1st_subsurface.log](https://github.com/libdivecomputer/libdivecomputer/files/4303525/1st_subsurface.log)

**Comment by jefdriesen** [comment] 2020-03-08 19:07
The Ratio dive computers are Bluetooth Classic (rfcomm) only.

The download looks fine, except for the last part, where it seems to be stuck in an endless loop with this line repeating:
```
INFO: Read: size=0, data=
INFO: Read: size=0, data=
INFO: Read: size=0, data=
```
Could this be a bug in the subsurface custom I/O implementation? Because with libdivecomputer's builtin rfcomm there was no such problem.

**Comment by linuxcrash** [comment] 2020-03-13 11:46
@jefdriesen @dirkhh is there anything specific I can do to get you all more details on this? I'm unfortunately not familiar with the I/O code and as such cannot really debugg the issue here. But if anyone can get me some guidlines how to provide the necessary information I'm happy to do so.

**Comment by jefdriesen** [comment] 2020-03-13 12:41
This is a bug in the subsurface fork of libdivecomputer:
https://github.com/Subsurface-divelog/libdc/blob/Subsurface-NG/src/iostream.c#L189

The read callback returned 0 bytes with status code DC_STATUS_SUCCESS. The 0 bytes are obvious from the logged `INFO: Read: size=0, data=` line. Any other status code would cause the function to return. Since we see the same line repeating, that's not the case. Thus as long as the read callback returns zero with DC_STATUS_SUCCESS, the while loop never ends.

The standard libdivecomputer code does not have this problem because there is no such loop:
https://github.com/libdivecomputer/libdivecomputer/blob/master/src/iostream.c#L189
That explains why downloading with dctool works.

When looking at the qt_serial_read function:
https://github.com/Subsurface-divelog/subsurface/blob/master/core/qtserialbluetooth.cpp#L132
there are indeed two cases when this function can return early:
```
device->socket->state() != QBluetoothSocket::ConnectedState
```
and
```
if (!timer.isActive())
	break;
```
For the first case, the code should probably return an error like DC_STATUS_IO. And for the second case DC_STATUS_TIMEOUT, if we didn't get enough bytes.

**Comment by torvalds** [comment] 2020-03-13 17:42
@jefdriesen @linuxcrash this is hopefully fixed by

https://github.com/Subsurface-divelog/subsurface/pull/2673

**Closed** 2020-03-15 12:05 UTC
