### ISSUE TITLE
RTS signal handling for Pelagic data cables

### ISSUE THREAD

**Issue by bperrybap** [libdivecomputer/libdivecomputer#4] opened 2018-09-14 22:13 UTC
The RTS signal needs to be low before it is raised when starting Pelagic cable initialization to ensure that the data cable initialization sequence can start clean and always succeed.
This is not always happening in certain environments like android when using libusb.
The RTS signal should be lowered for 100ms first, then raised, not just set.
This ensures that the PIC inside the data cable is reset and things start from a common known state every time regardless of the state of the signal when the data cable initialization code is started.
Currently, the code is not doing this and there are cases where initialization fails - like on Android where libusb is used and the RTS signal remains set after the app is finish using the device as there is no device driver taking over at close() time to reset the signals.
Correcting this definitely affects the code in oceanic_vtpro_device_open() in oceanic_vtpro.c and likely code for other pelagic dive computers as well.
For example, if you do a download on Subsurface Mobile from an Aeris Atmos AI using an Oceanic data cable, if you try to do another download - without unplugging the data cable, the download will fail since the PIC will not respond to the MOD mode init command (0xAA 0x00) and the download will fail until the data cable is yanked and re-inserted.

Background & details:
I am most familiar with the Aeris Atmos AI and the associated Aeris & Oceanic data cables.

There is a PIC16C622A  microprocessor inside the USB data cables for the group 1 and group 2 dive computers and I'm assuming also for the group 3 computers.
There is a PIC microcontroller inside the data cable that that is responsible for talking to the PDC.
Before we can communicate with the PDC, a few conditions must be met.
1. We have to properly initialize the PIC inside data cable.
2. We have to put the PDC into "download" mode.

The PIC starts running from a default state when RTS goes from low to high.
If there is no transition, the PIC remains in its current state.
The PIC requires an initial initialization command, (0xAA,0x00) or (0x20,00) in oceanic_vt_pro_init()
The PIC will only respond to this initial "init" command when it is in a default state and has not already received and responded to this command.
The only want to get the PIC to return to or be in a known state where it can accept this command is to reset it by dropping RTS then raising RTS.

So the RTS line needs to start low then go high. To ensure that this always happens, the code should first set RTS low, wait 100ms, then raise it up where it can then wait the needed time before sending that initial init command. It should not depend on any outside code to be previously setting the RTS to low.

While setting RTS to low could be done in the device close function like oceanic_vtpro_device_close() I think it is better to have the device open function set it low before setting it high so that it does not care about the initial RTS state so it can work in any environment including after an application crash that didn't call the close function to set RTS back low.

I would recommend something like this code for down in oceanic_vtpro_device_open()
it is essentially adding code to drop RTS low for 100ms before continuing on with the existing code.
```
	// Set the timeout for receiving data (3000 ms).
	status = dc_iostream_set_timeout (device->iostream, 3000);
	if (status != DC_STATUS_SUCCESS) {
		ERROR (context, "Failed to set the timeout.");
		goto error_free;
	}

	// Set the RTS line low to reset PIC inside the data cable
	// this ensures that the PIC will start in a known state
	// as it won't respond to init commands unless it is in
	// a default power-up state.
	status = dc_iostream_set_rts (device->iostream, 0);
	if (status != DC_STATUS_SUCCESS) {
		ERROR (context, "Failed to set the RTS line.");
		goto error_free;
	}

	// hold RTS down for a bit to allow reset to happen
	dc_iostream_sleep (device->iostream, 100);

	// Set the DTR line.
	status = dc_iostream_set_dtr (device->iostream, 1);
	if (status != DC_STATUS_SUCCESS) {
		ERROR (context, "Failed to set the DTR line.");
		goto error_free;
	}

	// Set the RTS line to get the PIC going
	status = dc_iostream_set_rts (device->iostream, 1);
	if (status != DC_STATUS_SUCCESS) {
		ERROR (context, "Failed to set the RTS line.");
		goto error_free;
	}

	// Give the interface 100 ms to settle and draw power up.
	dc_iostream_sleep (device->iostream, device->protocol == MOD ? 100 : 1000);

	// Make sure everything is in a sane state.
	dc_iostream_purge (device->iostream, DC_DIRECTION_ALL);
```

I've been using a sequence similar to this (I don't mess with DTR) in a downloader tool I've had working with an atmos AI for over 10 years.

**Comment by jefdriesen** [comment] 2018-09-15 06:56
This looks fine to me. I'm not sure whether the INTR variant of the protocol also needs the RTS toggling, but even if it doesn't, it probably doesn't cause any harm. I would also move the DTR call a bit earlier, just after the timeout. That way it's out of the way of the RTS toggling, which makes the toggling a bit more easy to see.

About that DTR line: It's been a while, but the DTR line is most likely set because the Oceanic application did the same, and I just copied this. Note that on windows the state of the DTR and RTS lines are always initialized when modifying one of the other serial line settings. So even if it's not really used for anything, it will be initialized anyway.

Will you send a patch, or should I turn this into a patch for you?

**Comment by bperrybap** [comment] 2018-09-15 15:42
I'll do build with the RTS handling in the vtpro code and test it on my Atmos AI with Subsurface mobile just to verify that it doesn't break anything. And get back with results.
After that we can decide on the patch.

Some other thoughts.
Not sure about how the signals are handled in Win10 (I've never used it), but over the decades I've seen Microsoft screw up DTR and RTS handling in multiple different ways.
In various versions of 98 and XP I saw them control the wrong one at open time (setting RTS instead of DTR), or even get them backwards. And for a while there was an issue in the FTDI driver that got the DTR and RTS signal handling backwards which really confused things - this same FTDI driver bug was even in linux for a while. And things broke again when the FTDI driver got fixed. Things were pretty bad for a couple of years during this period with respect to getting DTR and RTS signals to work properly.
For a while Windows even had the ability in the advanced settings to set the DTR and RTS behavior including using RTS for h/w flow control so signal behavior could vary on an individual basis. (but depending on which OS and which FTDI library you had the DTR and RTS signals used and/or specified might be backwards).
At one point I even saw that the FTDI chip configuration was altered to swap the RTS and DTR pins as a work around which created its own set of issues/confusion.

It could be that the Oceanic s/w toggled both just to be sure they got RTS to be low before they started the init sequence.

These days I think DTR and RTS are working correctly in Windows and Linux where DTR is set at file open time and RTS is left alone but can be controlled by the application or in some cases used for h/w flow control. Not sure if either clears RTS at close()

**Comment by bperrybap** [comment] 2018-09-16 16:44
> I would also move the DTR call a bit earlier, just after the timeout. That way it's out of the way of the RTS toggling, which makes the toggling a bit more easy to see.

I agree.
I tested this modification in oceanic_vtpro.c with the Atmos AI and it works great. It is now possible to do multiple downloads with Subsurface mobile without having to yank an re-insert the data cable.
Here is the update.
Change this:
```
        // Set the RTS line.
        status = dc_iostream_set_rts (device->iostream, 1);
        if (status != DC_STATUS_SUCCESS) {
                ERROR (context, "Failed to set the RTS line.");
                goto error_free;
        }

```
to this:
```
        // clear RTS line to reset the PIC inside the data cable as it may not have
        // have been previously cleared.
        // this ensures that the PIC will always start in a known state once RTS is set.
        // starting in a known default state is very important as the PIC won't respond to
        // init commands unless it is in a default state.
        status = dc_iostream_set_rts (device->iostream, 0);
        if (status != DC_STATUS_SUCCESS) {
                ERROR (context, "Failed to clear the RTS line.");
                goto error_free;
        }

        // hold RTS clear for a bit to allow PIC to reset
        dc_iostream_sleep (device->iostream, 100);

        // Set the RTS line to get the PIC going
        status = dc_iostream_set_rts (device->iostream, 1);
        if (status != DC_STATUS_SUCCESS) {
                ERROR (context, "Failed to set the RTS line.");
                goto error_free;
        }
```
In terms of a PR, I have some uncertainties about certain modules.
While I know it works in oceanic_vtpro.c 
I'm assuming that the update should also be put into in these modules since they are using the oceanic data cable.
oceanic_atom2.c
oceanic_veo250.c
oceanic_vtpro.c

And the update is probably ok for these as well:
mares_darwin.c
mares_nemo.c

but I'm concerned about some of the other modules like this one that does some other DTR signal twiddling
cressi_leonardo.c

I think it will be best if I leave the decision as to which ones to update beyond oceanic_vtpro.c to you so that I don't break something and it will also ensure that all the modules that need it can all be updated in the same single patch.

**Comment by bperrybap** [comment] 2018-09-18 15:31
> Thus in order to achieve the same initial state on all platforms, the libdivecomputer backends explicitly sets both the DTR/RTS lines after configuring the serial line settings. 

But it isn't ensuring that everything is starting from the same initial state on all platforms.
It is merely ensuring that both DTR and RTS are both set. That isn't good enough.
It is critical that RTS must start from the cleared state. And that isn't happening on some platforms.

I can say with 100% certainty that this RTS change isn't about the dive computer being used.
It is about the data cable itself.
So it affects all dive computers that use the same data cable or a data cable of a similar design.
It appears that you are thinking that the host talks to the dive computer but
the host does not talk to the dive computer. That isn't how it works.
There is a PIC micro-controller that sits between the FTDI chip and the signals that connect to the PDC.
The host talks to a PIC inside the data cable and the PIC talks to the PDC.
The PIC is what processes all the commands.
That PIC inside the data cable must be properly initialized before it will process commands to transfer data to/from the actual dive computer.
Remember that there are two things that must happen to be able to retrieve dive computer data
1)    initialize the PIC inside data cable.
2)    Tell the PIC to put the PDC into "download" mode.

This RTS change is about getting the PIC inside the data cable to a known state so it can be initialized to then allow further commands that communicate with the dive computer.
This is completely independent of the dive computer attached to the data cable or whether there is even a dive computer attached at all.

The PIC must first be initialized; then, the PIC can be told to put the PDC into download mode.
The commands sent through the data cable are processed by the PIC not the PDC.
That first initialization command that is sent (0xAA,0x00) or (0x20,00) in oceanic_vt_pro_init() is to initialized the PIC, it does not require that a PDC even be attached to the data cable.
i.e. the PIC will respond to that command regardless of whether the PDC is attached or in countdown mode.

The issue is that the PIC will only respond to that initial command if is in a default state.
The only way to get the PIC into that default state is to clear RTS and then set RTS.
Just setting RTS isn't good enough to ensure that the PIC is in the proper state as RTS might have already been set.
If you do not have RTS clear before setting RTS,  the AA/00 or 20/00 command will be ignored and the PIC will appear to be deaf.
So starting with RTS cleared  is critical to get the PIC back into a state where it can process that first command.

In most cases it appears that the current backend code is working because other code outside the libdivecompuer code (like an OS driver) is clearing RTS before the libdivecomputer code is run.
But this isn't always the case - like when libusb is being used in something like Subsurface mobile.

For robustness, libdivecomputer should not depend on outside code to control the RTS signal for it.

This RTS update ensures that the RTS signal always starts in a cleared stated regardless of the environment, (Windows, Linux, MAC, IOS, or libusb). This ensures that the PIC is in a known state so that the first initialization command will succeed. 

While I've extensively tested on this on the Oceanic data cable part no 04.9600  (over many years) my suspicion is that the other Pelagic data cables use a similar if not the same internal design and so it would be useful to always start the RTS signal at a known cleared state rather than depend on it being cleared by s/w outside libdivecomputer.

And even if the other data cables use a different design that does not require the RTS signal to start off cleared, it won't hurt anything to clear RTS prior to setting it to ensure that things always start of in a common state regardless of environment rather than depend on external code to clear RTS which currently, isn't always happening.

It wouldn't take much to test this on other data cables. All you have to do is send that first initial command to the data cable and see if it responds when no dive computer is attached. 
Then send it again while the port is still opened. You can see that it won't respond again until RTS is lowered and then raised again.

**Comment by bperrybap** [comment] 2018-09-18 16:14
Point of clarification. If the data cable was just plugged in, the PIC will be in the default state.
The most common failure usage case is attempting to talk to data cable after having just previously used the data cable - and then trying to use it again (without unplugging/re-plugging it), but RTS is still set from the previous usage.

**Comment by jefdriesen** [comment] 2018-09-19 12:27
> But it isn't ensuring that everything is starting from the same initial state on all platforms.
> It is merely ensuring that both DTR and RTS are both set. That isn't good enough.
> It is critical that RTS must start from the cleared state. And that isn't happening on some platforms.

I was indeed referring to the state of the serial port, not the state of the device behind it. That are two different things. I only tried to explain why libdivecomputer also initializes DTR, even when it's maybe not strictly needed. This was not about the RTS toggling.

> I can say with 100% certainty that this RTS change isn't about the dive computer being used.
> It is about the data cable itself.
> So it affects all dive computers that use the same data cable or a data cable of a similar design.

Exactly. That's why I mentioned that there are several variants of the Pelagic data cable. I simply don't know how similar those cables are. The newer generations could be (and probably are) very different from the older generations. Anyway, I did some more searching, and found this:

https://www.oceanicworldwide.com/us/faq/download-support/Personal_Dive_Computer_and_USB_Computer_Interface_Cable_Compatibility

So there are at least 4 variants, and apparently there is also a 5th variant (04-9612) with a round connector for the watch style dive computers:

https://www.leisurepro.com/Image/Product/Large/OCNPCUSB4.jpg

> It appears that you are thinking that the host talks to the dive computer but
> the host does not talk to the dive computer. That isn't how it works.
> ...

No, I'm well aware of the intermediate micro controller, and the reason why the RTS toggling is necessary. And your reasoning that everything usually works fine even without the toggling due to some external factors (e.g. platform drivers) is probably correct too. But we should at least try to confirm those suspicions with some real testing. If those tests show no problem, then I have absolutely no objections to apply the fix to all three pelagic backends. That's what I meant to say.

So let's prepare a test build, and distribute it to a few oceanic users...

**Comment by bperrybap** [comment] 2018-09-19 17:59
Just a bit of clarification, it really isn't toggling RTS.
It is that the RTS must be clear for some period of time prior to it being set before starting the data cable/PIC initialization command sequence.

In terms of testing , there should be no need to do any further testing with the other dive computers that use oceanic_vtpro.c code since this issue is related to the data cable not the dive computer so it will affect all dive computers supported in that module that use the Oceanic or Aeris data cable.  (which is what I assume you were saying).

For the others, if I had to guess, I assuming that they will also benefit from initially lowering RTS in the data cable initialization code as well since I'm assuming that they use the same internal data cable design.

At one point during my testing I went to ScubaToys with a laptop about 9 or 10 years ago.
They let me do some testing with any/all data cables that they had at the time and they all worked this way.
I tested on 4 or 5  different data cables.
This included on a data cable what was a clip for one of the watch style computers, and a "newer" data cable that used the same 3 pin connector but was a much smaller round dongle vs the larger square/block dongle used on the Oceanic data cable that I have. It was used on some devices like the HUD mask.
I even used the newer/small round dongle to do an actual downloads on my Atmos AI.
There have been some newer data cables that were released since then so those may be totally different.

Not sure if you remember but we did talk about this back then (9+ years ago) when libdivecomputer was just getting started.  I was really pushing for the code to clear RTS prior to setting RTS  before it started the initialization command sequence to ensure it would always work.

How are you thinking about testing for this?
This testing would need to be done in an environment where external s/w (like an OS driver) is not clearing RTS.

What type of special test build s/w are you thinking?
A specialized custom app or a custom version of Subsurface mobile?

I have a custom command line app which is how I do my testing.

You can actually test this manually with just a terminal emulator and the data cable attached (no computer needed) if you have a way to set/clear RTS.
You simply connect to the data cable and the right speed,  set RTS, send the first command.
You should see the response from the PIC.
Send it again and see if you get a response.
If  you get a response,  clear RTS prior to setting it isn't required.
If you don't get a response,  clear RTS, then set RTS and send the first initialization command.
If you now get a response, then you know that RTS must start clear when the init sequence starts.
But it still isn't a toggle. It is just that RTS must be clear for some period of time prior to setting it when starting the initialization sequence.

BTW, I have seen at least one recent feedback on the playstore from a Mares user using a data cable where it wasn't working. There were some timing issues in subsurface that have now been fixed, so that may have resolved his issue but it might worth tracking down that guy to have him try whatever special s/w you are thinking about.

**Comment by jefdriesen** [comment] 2018-09-21 13:18
> How are you thinking about testing for this?
> This testing would need to be done in an environment where external s/w (like an OS driver) is not clearing RTS.

It can be even simpler. You tested the RTS "toggling" (which is indeed about the transition from clear to set), so we already know that's fine. What we don't know for sure is whether applying the proposed fix would break anything for other models (using different variants of the cable). Probably not, but we better confirm that before deploying the fix to everyone. So we just need to test a normal build with the fix applied, and have it tested by a few people. If no problems show up, we're done.

I prepared builds of libdivecomputer's dctool command-line application here:

https://libdivecomputer.org/builds/experimental/windows/dctool-rts.exe
https://libdivecomputer.org/builds/experimental/macosx/dctool-rts
https://libdivecomputer.org/builds/experimental/linux/dctool-rts

With this patch applied:

https://libdivecomputer.org/tmp/0001-Fix-the-RTS-signal-handling-for-Pelagic-interface.patch

BTW, I forgot to mention this, but the reason why I suspect that the PC interface for the newer atom2 based models might be different from the others, is because the atom2 protocol does not require a command to initialize the cable. So that's quite different compared to the vtpro and veo250 protocols. On the other hand, I don't have any explanation why the 04-9604 and 04-9606 cable appears to support devices using the veo250 protocol (Veo 150, Veo 180, Veo 200 and Veo 250) AND the atom2 protocol (Datamask, VT4, VT3, Pro Plus 2.1, Veo 2.0 and Veo 3.0).

> BTW, I have seen at least one recent feedback on the playstore from a Mares user using a data cable where it wasn't working. There were some timing issues in subsurface that have now been fixed, so that may have resolved his issue but it might worth tracking down that guy to have him try whatever special s/w you are thinking about.

That was a completely different issue.

**Comment by bperrybap** [comment] 2018-09-21 16:15
I agree that testing is a good thing,  but looking at it from a big picture point of view, the backend code is currently setting RTS. This means that it is assuming that when that backend code is run, that RTS is either clear or might be clear but that RTS needs it to be set so it is setting RTS to ensure RTS is set before starting the initialization commands.
So given that the code assumes RTS could be clear prior to it running, then I can' t imagine how explicitly clearing it in that code just prior to setting it could cause any issues, especially since RTS being cleared before the backend code is called is already happening.
But it won't hurt to do some testing.


What does the test code actually do?
I can hook up a logic analyzer and look at the FTDI chip to see the signals and timing on linux.

Does it try to do anything special beyond a normal download like attempting to do multiple downloads without closing the serial connection/device between downloads?
Does it use an OS device or libusb? (this can make a difference)
The environment that I see the issue is Subsurface mobile on Android which uses libusb to talk to the FTDI chip. In that libusb environment, RTS is not messed with unless the app specifically does something to it so once RTS is set it by the backend code, it remains set until the cable is yanked an re-inserted. 
This is what creates an issue at least with the Oceanic 04.9600 data cable as once a download attempt has been done, RTS is stuck set, no other download can be done until the cable is yanked, unless the RTS clear patch is in place.

In terms of testing to learn things,  the type of testing depends on the goal.
If the goal is to determine if RTS being cleared before the current initialization sequence is truly necessary, then just running patched code that clears RTS  is not  good enough to know if RTS starting cleared is actually required.
While it can provide a data point of information as to whether clearing RTS appears to break something, to be able to confirm its necessity requires more specialized code to be able to see if the PIC goes deaf to future initialization sequences after a successful initialization unless RTS is first cleared.


On the Mares stuff, I mainly meant the guy might be person that is willing to do some testing, as he likely has some motivation to help out to get things working. So he might be a candidate that could run some experimental test s/w like this.

**Comment by jefdriesen** [comment] 2018-11-19 09:45
Sorry for not getting back earlier, but the patch has now been applied with commit 6e87c1d7b7a79ceb09630bcf1b13f363314f4610. No regressions were found during testing with a few devices.

FYI, the linux kernel will automatically raise RTS and DTR when opening a serial port. Our Windows serial implementation does the same in the dc_serial_configure() call. So on those two platforms, the dive computer backends always start with RTS and DTR raised.

**Closed** 2018-11-19 09:45 UTC
